[package]
name = "mimic_common"
version = "0.1.0"
authors = ["martin <martin.papanek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
thiserror = "1.0.23"
nalgebra-glm = "0.9.0"
